apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threads
  namespace: prakarsa
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: no-middleware-dev-api.prakarsa.id/api/v1
      http:
        paths:
          - path: /threads
            pathType: Prefix
            backend:
              service:
                name: threads
                port:
                  number: 80