replicaCount: 1

image:
  repository: ghcr.io/sfdaus/thread
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: "no-middleware-dev-api.prakarsa.id"
  certResolver: le
  className: traefik

secretName: threads-env