replicaCount: 1

image:
  repository: ghcr.io/sfdaus/threads
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: "no-middleware-dev-api.prakarsa.id"
  certResolver: le
  className: traefik

imagePullSecrets:
  name: ghcr-secret

secretName: threads-env